---
- name: Restart Docker
  service:
    name: docker
    state: restarted

- name: Restart Grafana container
  become: yes
  docker_container:
    name: "{{ grafana_container_name }}"
    hostname: "{{ grafana_container_name }}"
    image: "{{ grafana_image }}"
    restart: yes
    published_ports:
      - 3000:3000
    volumes: "{{ grafana_volume_mountinstructions }}"
    links:
      - "{{ prometheus_container_name }}"
    env: "{{ grafana_environment_variables }}"
    restart_policy: always