##### The following script will install the required packages for a full installation
##### of Docker, the GPG key (to keep up to date), docker repository, and the Docker CE.
  - name: Install aptitude using apt
    apt:
      name: aptitude
      state: latest
      update_cache: yes
      force_apt_get: yes

  - name: Install required system packages
    apt:
      name: {{ item }}
      state: latest
      update_cache: yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      update_cache: yes
      name: docker-ce
      state: latest

  ### IMPORTANT: There will be an error if you ONLY have pip3 installed
  ### since Ansible's module of pip will jump straight to pip, not pip3.
  - name: Install Docker Module for Python
    pip:
      name: docker
      executable: pip3