---
####### Alert Manager Variables ########
### Overwrite the alert parameters with a secure email when receiving alerts.
## The alerts WILL BE in clear text so anyone can read it, definitely main providers
## such as Google, Yahoo, or AT&T. Make sure to use either Slack or a company such as
## ProtonMail. As long as it's secured.
alert_manager_source_email: root@localhost
alert_manager_source_password: default

alert_manager_container_image: prom/alertmanager
alert_manager_container_name: alert_manager
alert_manager_smtp_server: smtp.gmail.com:587
alert_manager_destination_email: root@localhost
alert_manager_config_file_name: alert_manager.yml
alert_manager_volume_source: /srv/alert_manager
alert_manager_volume_target: /etc/alertmanager/config.yml
alert_manager_volume_mountinstructions: "{{ alert_manager_volume_source }}/{{alert_manager_config_file_name}}:{{alert_manager_volume_target }}"
