### Grafana will be installed to /tmp directory where 2 plugines will be needed named as adduser and libfontconfig1.
### From here we install Grafana and enable the servers to start. To connect to the server, the URL is https://localhost:3000/.
---
- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.0.4_armhf.deb
    dest: /tmp
    cheksum: sha256:3efdbf596dbccba883ca58272f9d81fcbdc5990163fd75a8c358b20a802c8111

- name: Install adduser (Grafana prerequisite)
  become: yes
  apt:
    name: adduser
    state: present

- name: Install libfontconfig1 (Grafana prerequisite)
  become: yes
  apt:
    name: libfontconfig1
    state: present

- name: Install Grafana
  become: yes
  apt:
    deb: /tmp/grafana_7.0.4_armhf.deb

- name: Enable Grafana Service
  become: yes
  service:
    name: grafana-server
    state: started
    enabled: yes