---
# Creation of username for the server
create_user: romelben

# Copying of local key to a remote server for security purposes
copy_local_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

# Mother load of packages that will be installed on the environment. If you want to add
# more packages to your environment, please add in the packages name and if you want to install
# a specific version, edit the server-installation-playbook script. If you want to update to the latest build,
# copy and paste the GPG key and include the repository.
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'wget', 'aptitude', 'ca-certificates', 'gnupg2', 'software-properties-common', 'htop',
                'ansible', 'python3-pip', 'apt-transport-https', 'virtualenv', 'bash', 'ntp', 'ntpdate', 'gnupg-agent',
                'imwheel', 'blueman', 'deepin-terminal', 'docker-ce', 'code', 'terraform', 'vagrant', 'nodejs' ]

##### Node.js parameters
# Set the version of Node.js to install (8.x, 10.x, 12.x, 13.x, etc)
# Version numbers for NodeSource are as follows: https://github.com/nodesource/distributions
nodejs_version: "12.x"

# The directory for global installations
# npm_config_prefix: "/usr/local/lib/npm"

# Define a list of global packages to be installed with NPM
#nodejs_npm_global_packages: []
  # Install a specific version of a package.
#  - name: jslint
#    version: 0.9.3
  # Install the latest stable release of a package.
#  - name: node-sass
