# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# Here we have different job names which will "scrape" through our metrics for data.
# We currently have Raspberry Pi hosting node_exporter (which creates metrics for Linux) and
# Traefik
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
#    static_configs:
#         - targets: ['192.168.1.14:9090'] # Enter the IP address of the target host (Prometheus)
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.14:9100']    # Enter the IP address of the target host (Node Exporter)
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.14:8080']    # Enter the IP address of the target host (Traefik)

#  - job_name: 'cadvisor'
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
#    dns_sd_configs:
#    - names:
#      - 'tasks.cadvisor'
#      type: 'A'
#      port: 8080

#     static_configs:
#          - targets: ['cadvisor:8080']

#  - job_name: 'node-exporter'
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
#    dns_sd_configs:
#    - names:
#      - 'tasks.node-exporter'
#      type: 'A'
#      port: 9100

#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#      port: 9091

#     static_configs:
#          - targets: ['node-exporter:9100']

