---
- hosts: all
  become: true
  vars_files:
    - vars/server-setup.yml

  tasks:
###### Create wheel group
    - name: Setup 'wheel' group
      group:
        name: wheel
        state: present

    ### Setup wheel group to not have passwordless
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    ### Set created user to wheel group with sudo privilages
    - name: Create a regular user with sudo privilages to wheel group
      user:
        name: "{{ create_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash

###### IMPORTANT: Make sure to create an SSH key on your local computer.
###### This can be done using this command: ssh-keygen -t rsa -b 4096 -C "email_here@domain.com"
###### This will setup user, pull local SSH key from local computer, and disable password authentication for root
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    ### Complete setup of packages for Debian/Ubuntu distros
    - name: Update and install all required system packages
      apt:
        name: "{{ sys_packages }}"
        state: latest
        update_cache: yes

###### Setup Docker's GPG apt key, Docker CE, Docker Respository, as well as necessary packages to apt
###### (i.e. apt-transport-https, ca-certificates, curl, gnupg-agent, software-properities-common).
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

    - name: Install Docker-CE to targeted system
      apt:
        name: docker-ce
        state: present

    ### IMPORTANT: Make sure to executable has pip3 since Ansible's module of pip
    ### will jump straight to pip.
    - name: Install Docker module for Python
      pip:
        name: docker
        executable: pip3

###### Setup Oracle VirtualBox
#    - name: Install Oracle VirtualBox
#      apt:
#        name: virtualbox
#        state: present

#    - name: Install Virtual Extension Pack for Oracle VirtualBox
#      apt:
#        name: virtualbox—ext–pack
#        state: present

###### Copy, confirm, and setup NTP on distro
    - name: Copy over the NTP configuration
      template:
        src: ntp.conf
        dest: /etc/ntp.conf
      tags: ntp

    - name: Confirm if NTP has initiated
      service:
        name: ntp
        state: started
        enabled: yes
      tags: ntp

    - name: Restart NTP server
      service:
        name: ntp
        state: restarted

###### Firewall setup
    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming